name: ed25519_dart
description: Pure Dart implementation of Ed25519 - public-key signature system.
version: 1.0.2
homepage: https://github.com/semolex
author: Oleksii Semeshchuk <semolex@live.com>

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pointycastle: ^1.0.1
  hex: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
